info:
  app:
    password: swordfish
    name: @project.name@
    version: @project.version@
    description: @project.description@
    promo-code: paper
server:
  port: 8080
  servlet:
    context-path: /
spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate.format_sql: true
  datasource:
    username: sa
    password: password
    url: jdbc:h2:mem:dagacube
    driver-class-name: org.h2.Driver
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
logging:
  level:
    org:
      hibernate:
        type: TRACE
